from __future__ import absolute_import
from __future__ import division
from __future__ import print_function

from zodiac_web.sequence_service_decorator import sequence_service
from zodiac_web.web_service_loader import WebServiceLoader